69 mvp1 button
nology-tech/venturist-client-project pull request #35
Opened 2022-02-23 16:40 UTC by lae321

Basic functionality of button. Default and dynamic styling. Still needs updating with variables specified by the variables team.

2022-02-24 09:05 UTC, WilliamBusby requested changes
Button.test.js has to have some content in for this to pass as the tests fail otherwise. 

You can take the basic test from App.test.js as this will always pass until you add some actual tests to the file

2022-02-24 15:40 UTC, WilliamBusby requested changes
Icon can be on the left or right? So where some option to use left or right icon position

2022-02-28 16:47 UTC, WilliamBusby requested changes
Titles should say what each icon relates to (also need to change line 31 in test for this).

Not sure where the css3-fill.png is used? If unnecessary remove it

2022-02-28 16:55 UTC, WilliamBusby approved these changes

2022-02-28 16:59 UTC, seanpursani approved these changes

2022-02-28 16:59 UTC, merged